const BONUS = {
    WALLET_CONNECT : 1000,
    JOIN_TG_CHANNEL : 300,
    JOIN_TG_GROUP : 250,
    FOLLOW_X_ACCOUNT : 300,
    SUBSCRIBE_YOUTUBE: 20,
    VISIT_WEBSITE: 10,
    DAILY_REWARD : 100,
    RETWEET_POST : 250,
    SIGN_UP : 500,
    INVITE_FRIEND : 100,
    INVITE_FRIEND_WITH_PREMIUM : 200,
}
const TELEGRAM = {
    CHANNEL_ID: '-1001335748408',
    GROUP_ID: '-1002151631024'
}

const LEADERBOARD_SHOW_USER_COUNT = 500;

const VERIFY_TRANSACTION_ON_MAINNET = false;
const OWNER_ADDRESS = 'UQADlThF2_zCkpo_MYhO7IXUeO31ooNLB_A_SMcZHdAKf5qk';

module.exports = {
    BONUS, TELEGRAM, LEADERBOARD_SHOW_USER_COUNT, VERIFY_TRANSACTION_ON_MAINNET, OWNER_ADDRESS
};
